### ISSUE TITLE
Missing LaTeX commands: `\land` and `\lor`

### ISSUE THREAD

**Issue by xpe** [venkatasg/DeTeXt#6]
DeTeXt doesn't know about `\land`:

<img width="802" alt="image" src="https://github.com/venkatasg/DeTeXt/assets/4576329/c59eef0e-4173-48d6-9cc6-9ddf0d9773ac">

DeTeXt doesn't know about `\lor`:

<img width="802" alt="image" src="https://github.com/venkatasg/DeTeXt/assets/4576329/f89cf03f-0578-4d22-b65d-483728638974">

**Comment by xpe** [comment]
I have a guess as the source of the mistake: `\land` and `\wedge` are synonymous. Maybe DeTeXt does not correctly import and handle synonymous commands?

See also:

* https://tex.stackexchange.com/questions/23792/logical-and-character-in-tex-⋀

**Comment by xpe** [comment]
The list of LaTeX commands to import can be found here: https://github.com/venkatasg/DeTeXt-Supplementary/blob/main/class_names.txt -- as I suspected, `\wedge` is present but `\land` and `\lor` are missing.

This is the definitive list from what I can tell : https://ctan.org/pkg/comprehensive?lang=en

**Comment by venkatasg** [comment]
Yeah I only include commands that are in my training set of images, which are from the Detexify public repository. If I don't have data for a particular command, I don't include those commands since the neural network won't recognize them anyway.

**Comment by xpe** [comment]
@venkatasg Ok, thanks. What Detexify repository has the training images? Perhaps I can contribute over there.

**Comment by venkatasg** [comment]
It isn't actively maintained anymore unfortunately, but here it is: https://github.com/kirel/detexify-data

**Comment by venkatasg** [comment]
Beyond training dataset.
