### ISSUE TITLE
[Feature request] Trackpad Handwriting

### ISSUE THREAD

**Issue by ChengxianJin** [venkatasg/DeTeXt#7]
LOVE THE APP!!! Saved my life when writing papers.

However, as a MacBook user with only a trackpad, I'd love to have the option to toggle on trackpad handwriting (where your finger can simply touch the trackpad as if interacting on a mobile screen, without exerting any pressure, and the drawing will register). I believe this is a feature that Detexify has, and I'd love to see it being added here in this amazing app!

**Comment by venkatasg** [comment]
Hmm right now it is possible to draw using three-finger drag &mdash; which may need to be enabled in System Settings > Accessibility > Pointer Control > Trackpad Options > Set 'Dragging style' to Three Finger Drag. I think this is better than trying to implement drawing with single finger (if even possible on macOS) as this may register a false drawing anytime the cursor goes over the drawing canvas of the open DeTeXt window.

Closing this feature request for this reason. Thank you for the feedback though! Hope three finger drag satisfies your use case for drawing quickly.
